### ISSUE TITLE
pages以下のファイル名について

### ISSUE THREAD

**Issue by k-logic563** [Etakira224/QinSalonTeamDevelopment#1]
大文字からではなく、小文字から始めるのが自然なのかな、と思いました。
ドキュメントや他の記事をみても大文字から始めるのはなかったので、統一させた方がいいかもしれませんね！

**Comment by Etakira224** [comment]
ありがとうございます！
統一させておきます。ファイル名の慣例など、独学だと自己流になってしまいがちだったので、ご指摘いただけると大変ありがたいです。今後もよろしくお願いいたします。

**Comment by k-logic563** [comment]
@Etakira224 
こちら調べてみると、小文字の方がいい理由が見つかりました。

Google検索チームによると、以下のことが言われているそうです。
・大文字が入っていると**ユーザーが文字を見間違えてしまう可能性**があるよって小文字が好ましい

**Comment by Etakira224** [comment]
@k-logic563 
追記ありがとうございます。ユーザー側の視認性の問題が主ということですね。
文字の大小にも敏感になっていこうと思います。
