### ISSUE TITLE
不要なコメントの削除

### ISSUE THREAD

**Issue by k-logic563** [Etakira224/QinSalonTeamDevelopment#3]
https://github.com/Etakira224/QinSalonTeamDevelopment/blob/fa8d1b4bc9d14690be4905058c3b748e577779b8/components/organisms/GeneralHeader.tsx#L76-L80

こちらは使用されていませんかね？
不要なコメントは残しておくと後々混乱する元になりそうです...削除しておいた方がいいかもですね！

**Comment by Etakira224** [comment]
ありがとうございます。使用していませんね…。削除しておきます。
思いついたものを書く→後で使うかもと思って残しておく→ごちゃごちゃさせてしまう、という癖があるみたいです。こまめに削除していくようにします。
