### ISSUE TITLE
コピーライト表記について

### ISSUE THREAD

**Issue by k-logic563** [Etakira224/QinSalonTeamDevelopment#4]
https://github.com/Etakira224/QinSalonTeamDevelopment/blob/fa8d1b4bc9d14690be4905058c3b748e577779b8/components/organisms/Footer.tsx#L53

こちらは特殊文字なので、HTMLにそのまま記述すると文字化けを起こす場合があります。
以下のように記述しましょう！
`&copy;`

**Comment by Etakira224** [comment]
ありがとうございます！特殊文字まで気が回っていませんでした。修正しておきます！
